<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://WS" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://WS" xmlns:intf="http://WS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="WebServices">

   </wsdl:portType>

   <wsdl:binding name="WebServicesSoapBinding" type="impl:WebServices">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="WebServicesService">

      <wsdl:port binding="impl:WebServicesSoapBinding" name="WebServices">

         <wsdlsoap:address location="http://localhost:8080/uytubeweb/services/WebServices"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
